name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ zip openjdk-17-jdk kotlin
        sudo snap install dotnet-sdk --classic
        if [ ! -e /usr/bin/dotnet ]; then
          sudo ln -s /snap/dotnet-sdk/current/dotnet /usr/bin/dotnet
        fi

    - name: Create build folder
      run: mkdir -p build

    # ==== C++ 빌드 ====
    - name: Build C++ files
      run: |
        find DesignPattern -name "*.cpp" | while read file; do
          name=$(basename "$file" .cpp)
          g++ "$file" -o "build/${name}_cpp.out"
        done

    # ==== Kotlin 빌드 ====
    - name: Build Kotlin files
      run: |
        find DesignPattern -name "*.kt" | while read file; do
          name=$(basename "$file" .kt)
          kotlinc "$file" -include-runtime -d "build/${name}_kt.jar"
        done

    # ==== C# 빌드 ====
    - name: Build C# projects
      run: |
        find DesignPattern -name "*.csproj" | while read proj; do
          dir=$(dirname "$proj")
          name=$(basename "$dir")
          dotnet publish "$proj" -c Release -o build/$name
        done

    # ==== 미리 빌드된 JAR 복사 ====
    - name: Copy existing .jar files
      run: |
        find DesignPattern -name "*.jar" | while read file; do
          cp "$file" build/
        done

    # ==== zip 압축 ====
    - name: Zip build outputs
      run: zip -r build_artifacts.zip build/

    # ==== GitHub 릴리즈 생성 ====
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push'
      with:
        name: Auto Release - ${{ github.sha }}
        tag_name: release-${{ github.run_number }}
        files: build_artifacts.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
