name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ zip openjdk-17-jdk kotlin
        if ! command -v dotnet &> /dev/null; then
          sudo snap install dotnet-sdk --classic
        fi

    - name: Create build folder
      run: mkdir -p build

    # 디버깅: 모든 빌드 대상 파일 출력
    - name: Debug - List all source files
      run: |
        echo "C++ files:"
        find DesignPattern -name "*.cpp"
        echo "Kotlin files:"
        find DesignPattern -name "*.kt"
        echo "C# projects:"
        find DesignPattern -name "*.csproj"

    # ==== C++ 빌드 ====
    - name: Build C++ files
      run: |
        find DesignPattern -name "*.cpp" | while read file; do
          name=$(basename "$file" .cpp)
          g++ "$file" -o "build/${name}_cpp.out"
        done

    # ==== Kotlin 빌드 ====
    - name: Build Kotlin files
      run: |
        find DesignPattern -name "*.kt" | while read file; do
          name=$(basename "$file" .kt)
          kotlinc "$file" -include-runtime -d "build/${name}_kt.jar"
        done

    # ==== C# 빌드 ====
    - name: Build C# projects
      run: |
        find DesignPattern -name "*.csproj" | while read proj; do
          dir=$(dirname "$proj")
          name=$(basename "$dir")
          dotnet publish "$proj" -c Release -o build/$name
        done

    # ==== 미리 빌드된 JAR 파일 복사 ====
    - name: Copy prebuilt .jar files
      run: |
        find DesignPattern -name "*.jar" | while read file; do
          cp "$file" build/
        done

    # 디버깅: build 폴더 안에 뭐가 있는지 확인
    - name: Debug - List build folder
      run: ls -R build

    # ==== ZIP 압축 ====
    - name: Zip build artifacts
      run: zip -r build_artifacts.zip build/

    # ==== 릴리즈 생성 ====
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push'
      with:
        name: Auto Release - ${{ github.sha }}
        tag_name: release-${{ github.run_number }}
        files: build_artifacts.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
