name: Build and Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y g++ zip openjdk-17-jdk kotlin wget apt-transport-https

        # Install .NET SDK (stable alternative to Snap)
        wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        rm packages-microsoft-prod.deb
        sudo apt update
        sudo apt install -y dotnet-sdk-7.0

    - name: Create build folder
      run: mkdir -p build

    # ==== Build C++ files ====
    - name: Compile C++ files
      run: |
        find DesignPattern -name "*.cpp" | while read file; do
          name=$(basename "$file" .cpp)
          g++ "$file" -o "build/${name}_cpp.out"
        done

    # ==== Build Kotlin files ====
    - name: Compile Kotlin files
      run: |
        find DesignPattern -name "*.kt" | while read file; do
          name=$(basename "$file" .kt)
          kotlinc "$file" -include-runtime -d "build/${name}_kt.jar"
        done

    # ==== Build C# .csproj files ====
    - name: Compile C# projects
      run: |
        find DesignPattern -name "*.csproj" | while read proj; do
          dir=$(dirname "$proj")
          name=$(basename "$dir")
          dotnet publish "$proj" -c Release -o build/$name
        done

    # ==== Copy existing .jar files ====
    - name: Copy prebuilt .jar files
      run: |
        find DesignPattern -name "*.jar" | while read file; do
          cp "$file" build/
        done

    # ==== Create zip file ====
    - name: Zip compiled outputs
      run: zip -r build_artifacts.zip build/

    # ==== Release ====
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: github.event_name == 'push'
      with:
        name: Auto Release - ${{ github.sha }}
        tag_name: release-${{ github.run_number }}
        files: build_artifacts.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
